import React from 'react'

export const metadata = {
    title: 'About Page',
    description: 'Generated by create next app',
}

const layout = ({
    children,
}: {
    children: React.ReactNode
}) => {
    return (
        <div>
            <nav>About section</nav>
            {children}
        </div>
    )
}

export default layout
